#import "lib/template.typ": template
#import "lib/bibliography.typ": init-bib
#import "lib/utils.typ": *

#show: template.with(
  dedication: "Dedication or acknowledgements",
  // font: "New Computer Modern",
  font: "",
)

#let (cite, citesec, bibliography) = init-bib(yaml("BIBLIOGRAPHY.yml"))

= Introduction

Large Language Models (LLMs) have proven very useful in various contexts and types of users: some
only use them casually, some to help them study, while others use them to speed up their daily work.
This last category of people finds themselves often having to send prompts which contain private
information, such as parts of their company's code, contracts, or other material which is
intellectual property of the company and, as such, should remain private to the company itself.

While self-hosting open-weight models is always a possibility, individuals and companies often don't
have the required compute capabilities.
Usually entities which don't own their own hardware resort to inference providers (either the
provider of the model themselves or a third party one).
This however could become an issue because classical inference requires the users to sent plain text
to the inference provider, which then will come to know all the possibly private information which
users ask in their queries.

In this work we study an inference model based on Encrypted Matrix-Vector Products (EMVP for short)
#cite(<emvp2025>) which enables efficient computation of linear operations privately.
We study also how a GPT model can be distilled in order to remove as many non-linearities as
possible so that the remaining architecture is more suitable to be used with EMVP.

= Theory

== Encrypted Matrix-Vector Multiplication <sec:emvp>

The fundamental theoretical building block is the Encrypted Matrix-Vector Multiplication based on
Trapdoor Matrices #cite(<emvp2025>), in particular the construction based on the 1D-SLSN assumption.

The protocol works over a prime field $FF_p$. The client holds some matrix
$M in FF_p^(m times ell)$ and some vector $q in FF_p^(ell)$ and wants to delegate to an untrusted
server the computation of $a := M q in FF_p^m$.

To do this, the client encrypts $M ->^(#raw("sk")) hat(M)$ and $q ->^(#raw("sk")) (hat(q), q')$ and
sends $(hat(M), hat(q))$ to the server.
The server computes $M' in FF_p^(m times s)$, where $s$ is the number of blocks of the 1D-SLSN
construction (typically $s << ell$), and sends it back to the client. The client then recovers
$a = M' p' - r'$ from $(M', q')$, where $q' = (p', r')$ is its decoding key.

This protocol turns out to be particularly cheap to run compared to doing a matrix-vector
multiplication in clear text, only being $tilde 1.5$x more costly.

=== Protocol Description

The protocol is made of five algorithms:

/ Key Generation: Generate a private key `sk` for the client, taking as arguments a security
  parameter $lambda$ and the query length $ell$.
  Additional parameters to the EMVP protocol like the code rank $k$, and the 1D-SLSN block size $b$
  are derived from $(lambda, ell)$ using the algorithm presented in #citesec(<emvp2025>, "7.4").
/ Encryption: The client encrypts $M ->^(#raw("sk")) hat(M)$.
  It samples a secret multiplier $g <- FF_p^k$ which defines the systematic code
  $C = (I | M_g) in FF_p^(k times 2k)$ where $M_g$ is a circulant matrix generated by $g$
  #footnote[
    This is the cyclic ring variant presented in Section 3.1 of #cite(<emvp2025>). Since $M_g$ is
    circulant, encoding through $C$ or $D$ is a single cyclic convolution, computable in
    $bigO(k log k)$ field operations.
    Over this ring, however, the cyclic structure interacts badly with the 1D-SLSN block grid
    whenever the block size divides $k$; as prescribed in the same section, the implementation
    therefore permutes the codeword coordinates with a public random permutation $Pi$, applied
    consistently to $hat(M)$ and to every query.
  ].
  Together with its systematic dual $D := [ - M_g^T | I ] in FF_p^(k times 2k)$.
  Each row of $M$ is zero-padded to length $k$, encoded through $D$, masked by adding the
  materialization $R$ of a trapdoored matrix (TDM for short, see @sec:tdm), and permuted by $Pi$:
  $
    hat(M) := Pi (M_"pad" D + R) in FF_p^(m times 2k)
  $
  where $M_"pad"$ denotes $M$ with its rows zero-padded from $ell$ to $k$ coordinates.
/ Query: The client takes a vector $q$ and uses the secret key `sk` to produce the pair
  the encrypted query $hat(q)$ and the decoding key $q' = (p', r')$.
  We first sample $r <- FF_p^k$, then let $c := r^T C in FF^(2k)$ and $tilde(q) := q_"pad" + c$,
  where $q_"pad" in FF_p^k$ is $q$ padded with zeros.
  Then we compute $r' := R tilde(q)$ using the trapdoor in $R$.
  We proceed by sampling $alpha_1, ..., alpha_s <- FF_p without {0}$ and let
  $p' := (alpha_1^(-1), ..., alpha_s^(-1)) in FF_p^s$.
  We then partition $tilde(q)$ in $s$ blocks and multiply each one by $alpha_s$ in order to obtain
  $hat(q) = (alpha_1 q_1 | ... | alpha_s q_s)$.
  We return $(hat(q), (p', r'))$.
/ Answer: This is the only phase which _runs on the server_.
  The server gets $(hat(M), hat(q))$ and splits again in $s$ chunks and we compute
  $
    M' = [hat(M)_1 hat(q)_1 | ... | hat(M)_s hat(q)_s] in FF_p^(m times s)
  $
/ Decrypt: The client then computes $a = M'p' - r' in FF_p^m$.

=== Trapdoored Matrices <sec:tdm>

A Trapdoored Matrix (TDM) is formally defined as the pair $(R, #raw("apply"))$ where
- $R$ is a matrix over $F$, which is undistinguishable from one uniformly sampled from the same
  space;
- The function `apply`$: x mapsto R x$ which is a cheap, secret way to compute $R x$, also referred
  as _trapdoor_.

The TDM concept originates from two independent recursive constructions #cite(<braverman2025>, <vaikuntanathan2025>). In #citesec(<emvp2025>, "5") the authors describe several direct ways to
construct a TDM. In my work I considered three, each for a different reason.

/ Irreducible Ring-LPN: This is the TDM which has the strongest cryptographic foundation.
  The materialized matrix is $R = H E$ with $H = [I | M_a] in FF_p^(k times 2k)$, where the
  public block $M_a$ implements multiplication by a public scalar $a$ in a degree-$k$ irreducible
  extension of $FF_p$, and $E in FF_p^(2k times k)$ is a secret sparse Bernoulli matrix
  #citesec(<emvp2025>, "5.1").
  Pseudorandomness of $R$ then follows from the dual-LPN assumption over the extension ring, whose
  irreducible instantiation is the most conservative choice #cite(<heyse2012>, <boyle2022>).
  The trapdoor computes $x mapsto H (E x)$ as one sparse product followed by a single cyclic
  convolution, in $bigO(k log k)$ field operations.
/ Toeplitz fast product: The first conjecture-based candidate, which trades the LPN foundation
  for speed and universality #citesec(<emvp2025>, "5.2"). The matrix is a product of three
  secret Toeplitz factors interleaved with public random permutations,
  $
    R = S_L Pi_L S Pi_R S_R
  $
  where $S_L$ and $S_R^T$ are $k times 2k$ and $S$ is $2k times 2k$. Each factor is a cyclic
  convolution evaluated in $bigO(k log k)$ through a cached NTT spectrum, so the trapdoor never
  materializes $R$. Security rests on a conjectured degree-3 pseudorandomness property, a
  generalization of the MQ assumption #cite(<matsumoto1988>) whose track record warrants caution
  #cite(<beullens2022>).
/ RAA style: The leanest, most ad hoc candidate, modeled on repeat-accumulate-accumulate codes
  #cite(<divsalar1998>, <guruswami2008>, <brehm2024>). A fixed matrix $D$ repeats each of the
  $k$ input entries $c >= 3$ times, the result passes through rounds of public random
  permutations $Pi_i$ and secret weighted accumulations $S_i$, and $D^T$ finally compresses:
  $ R = D^T Pi_4 S_3 Pi_3 S_2 Pi_2 S_1 Pi_1 D $
  where $(S_i x)_j := sum_(l <= j) w_(i, l) x_l$ is a weighted prefix scan with secret weights,
  which the implementation evaluates with a linear-time scan #cite(<blelloch1993>). Every factor
  is a single linear pass, making this the cheapest of the three, but it inherits the same
  degree-3 conjecture #cite(<matsumoto1988>) with even less supporting analysis.

=== Cryptanalysis

None! I am NOT a cryptographer!

This work assumes that the assumptions in the cited documents are correct and does not try to prove
them independently.

I set the security parameter $lambda = 128$ in the project, but I haven't formally proven
independently that the whole protocol is secure against a malicious server.

My implementation should be correct and follows the constructions in the papers which provide the
algorithms but it hasn't been independently audited and might therefore be flawed.

== Linearization of the Transformer Model

The transformer model has become the de facto standard for language models.
Its basic unit, the _transformer block_ #cite(<vaswani2017>), maps a sequence of $d$-dimensional
token vectors to a new sequence of the same length through two sublayers: a self-attention
layer, and a feed-forward network, both wrapped in residual connections and normalization.

Both sublayers contain many linear parts, which are however interleaved by a non-negligible number
of non-linearities, which, as we discussed previously, require a roundtrip back to the client to be
computed. A single transformer block has 1 softmax, 1 activation (usually ReLU/GeLU/SiLU...), 2
normalization, moreover, even if self-attention is mostly linear, the score $Q K^T$ as well as the
final attention value $A V$ computations are linear operations on two input-dependent matrices and
therefore are not suitable for direct use with EMVP.

This issues can however be mitigated by the findings of these two studies which fit together almost
too well.

/ Your transformer is secretly linear: #cite(<razzhigaev2024>) is a study which highlights that
  often some of the transformer blocks can be well approximated by a suitable linear operation
  without losing much on performance.
/ AERO: #cite(<aero2024>) asks how many of the non-linearities of a transformer block can be removed
  without losing the quality of the output. The answer is surprisingly many, as long as you keep the
  entropy well balanced in the attention heads. After a suited training run, the whole attention
  block collapses to
  $
    Q = X W_Q, K = X W_K, V = X W_V \
    A = "Softmax"((Q K^t)/(t sqrt(d_k))), Z = A V \
    Y = X + "Concat"(Z_1, ..., Z_H) W_O
  $
  where we can let the client compute only $A$ and $Z$, which can become relatively small for an
  appropriate choice of weights matrices.

TODO: Expand here

== Related Works

TODO

= Assumptions

In this work I assume that all the cryptography assumptions in the EMVP protocol are sound and the
choice of parameters is appropriate. When I was in doubt on which parameters to pick I always made
the most conservative choice. This however does not guarantee safety.

Moreover I assume the client machine is fully trusted and that the client owns the weights of the
GPT, therefore the client is allowed to see intermediate values of the decoding process.

Computationally, the server is assumed to be more performant than the client and even have access to
a GPU, while the client is somewhat weaker, having access to a fairly modern multi-core CPU, in
particular one which supports AVX2 #cite(<intel-avx>).
I assume good connectivity between the client and the server: the better the connection the faster
the inference.

A stronger assumption would be that the server has a Trusted Execution Environment (TEE), in which
case the whole client can basically move to the TEE and reduce latency drastically as
non-linearities can be computed in the TEE without ever leaving the server. This study is however
out of scope for the current work.

= Development

== EMVP

TODO: add link to repo

I implemented the EMVP protocol in the Rust programming language #cite(<rust>), which provides the
memory safety and the low-level primitives needed for fast execution.

The result is a Cargo workspace containing five crates: two of them contain the application for the
client and the server, the remaining three implement the operations over a finite prime field,
trapdoor matrices, and the actual EMVP protocol.

Each one of the three library crates has been thoroughly tested and benchmarked. I highlight a few
implementation details which I find worth noting.

=== Prime Field Layer

This is really the core the project: all the algebra primitives are located here, therefore it's
important that the code is well optimized, as the performance of everything downstream depends on
them.

/ Vectorization:
  The whole crate is optimized having in mind that the client has access to an `AVX2`-capable CPU,
  which allows a substantial speedup in some algebraic kernels, such as computing NTTs,
  convolutions, dot products, and bulk operations in general.
  Interestingly, I found that LLVM optimizer #cite(<llvm>), when instructed to do so by setting
  `target-cpu = native`, and with some hints and trial and error, generates equivalent or faster
  machine code than handwriting `AVX2` intrinsics.
  This is great news, since it allows to drop the code complexity greatly, avoid many uses of
  `unsafe`, expand portability to non-`x86_64` platforms, like `ARM64`, and even support more
  advanced extensions, like `AVX512`.
  The only tradeoff is that clients have to compile their own version of the software: as this is
  research software I deemed the tradeoff worth it to see how much I could push the performance
  while keeping the project complexity in scope.

/ Compile time modulus:
  These optimizations by the LLVM compiler are also enabled by the fact that the `PrimeFieldLayer`
  struct takes the modulus $p$ as a _compile time_ parameter. This is acceptable since usually $p$
  is fixed beforehand and a program requires a single specialization of `PrimeFieldLayer` anyways.
  #footnote[
    I also wanted to move some length arguments to compile time, such as the size of TDMs, the
    length of the NTT, etc. However, even though I suppose this could lead to further performance
    gains, it effectively ties the compiled program to a single pretrained model (as sizes are
    compile time constants). Moreover, the Rust programming language at the time of writing does
    not support the right primitives to fully implement this idea, Zig #cite(<zig>) would be a
    better choice for this scenario, however it felt too unstable and unsafe to be used in this
    project.
  ]

/ Modular arithmetics:
  Multiplication runs in the Montgomery domain #cite(<montgomery1985>) so a product costs only
  multiplies and bit shifts while conversion happens only at the API boundaries.
  Constant multipliers, such as NTT twiddle factors, instead use Shoup's trick #cite(<shoup2009>):
  precomputing $floor(w dot 2^32 \/ p)$ replaces the reduction with one extra multiply and subtraction.
  All conditional corrections are expressed as branchless mask operations rather than
  comparisons, which lets LLVM vectorize the kernels.

/ Number Theoretical Transform:
  Instead of repeating the work for each transformation, we construct and hold a "plan" for a fixed
  length $N$: the plan computes a suitable root of unity, retains the twiddle factors in precomputed
  tables #cite(<frigo1999>), and picks which butterfly implementation fits the modulus width.
  The forward transform then walks $log_2 N$ stages in place, applying a butterfly to each pair of
  values. Each butterfly is Harvey's lazy variant #cite(<harvey2014>): instead of paying a full
  reduction after every addition and multiplication, residues are carried through in redundant
  intervals and each butterfly performs a single correction, and the slightly unreduced inputs feed
  directly into the wide-input form of Shoup's multiplication #cite(<bradbury2021>).
  A single normalization pass restores canonical residues once, after the last stage.

  Convolutions themselves proceeds in the usual three steps: transform both operands forward,
  multiply pointwise in Montgomery domain, transform the result back, and scale by $N^(-1)$.
  For negacyclic products modulo $x^N + 1$, the inputs are additionally twisted by powers of a
  $2N$-th root of unity before the transforms and untwisted afterwards #cite(<longa2016>).
  All of this reuses the plan's tables, so repeated products pay only the transforms themselves.
  Operands small enough that the $O(N log N)$ machinery is not worth it fall back to schoolbook
  multiplication below a crossover point measured with the benchmark suite.

  Even if this NTT implementation was independently written I compared it to other state of the art
  libraries which implement the same algorithm #cite(<concrete-ntt>, <fasterntt>).


=== Trapdoored Matrices

All TDMs implement the same trait: they need to provide an `apply()` method, which computes the
matrix vector product using the trapdoor, and a `materialize()` method, which returns the equivalent
public dense representation.
Moreover, I `apply()` to be allocation-free, therefore the implementers of the TDM trait should
provide a reusable scratch buffer.

The trapdoor matrix has less "science" behind it's optimizations: where feasible, intermediates are
cached and reused, and I use rayon #cite(<rayon>) to parallelize the paths which benchmarks show
benefit from parallel computation.

=== EMVP Protocol

TODO: rewrite this

This crate glues the previous two layers into the full protocol, so its speed comes less from
isolated kernels and more from structure: which work runs in which phase, how many times memory is
touched, and how much is allocated. These are the tricks which survived the benchmarks.

/ Answer kernel:
  The server's answer $M'$ consists of $m s$ dot products of length $b$ between blocks of $hat(M)$
  and blocks of $hat(q)$, making it the protocol's hottest loop. Accumulating into a single
  register serializes every step on the addition latency, so the kernel keeps four independent
  accumulators and folds them at the end. Each block is also sliced once up front, which removes
  the per-element bounds checks that the compiler cannot elide across the two operand slices.

/ Measured parallel crossover:
  Rows in the answer, encryption, and decoding loops are independent, so rayon #cite(<rayon>)
  distributes them across workers. Every parallel path is gated by a multiplication-count
  threshold calibrated once with the benchmark suite, plus the requirement of at least two rows
  per worker thread, so small inputs stay serial instead of paying scheduling overhead. Each
  worker allocates its scratch buffers once and reuses them for every row it receives, and every
  parallel path is tested to produce output identical to the serial loop, which lets the switch
  be made dynamically per workload.

/ Allocation-free online phase:
  Query and answer threads own reusable scratch structures, so steady-state queries allocate
  nothing. My favorite micro-trick: in the query algorithm $tilde(q)$ is dead once $r'$ and the
  permuted query have been computed, so its head doubles as staging for the $alpha_i$, and the
  decoding key $p' = (alpha_1^(-1), ..., alpha_s^(-1))$ comes out of a single batch inversion
  #cite(<montgomery1985>) without a fresh allocation. Batched answers for many queries are written
  into one query-major arena: a single allocation whose flattened (query, row) grid parallelizes
  without nested thread pools.

/ GPU hand-off:
  By our assumptions, the server has a GPU. During the answer phase, we can exploit its compute
  capabilities to compute the result faster.
  I chose to use WGPU #cite(<wgpu>, <wgsl>) instead of more popular alternatives like CUDA, as WGPU
  is open-source, cross-vendor, integrates well with Rust, and the performance loss is negligible
  for the scope of this project.
  Device buffers hold raw Montgomery residues, so uploads and readbacks move the words as-is: the
  answers are bit-identical to the CPU path with no conversion or normalization pass.
  Compute shares are also compiled on the flight for a specialized prime modulus, while the
  dimensions of each batch travel in a small uniform buffer, so changing protocol parameters never
  triggers a recompilation.
  // TODO: change below
  Device buffers are leased from a grow-only pool, so a server answering steady batch shapes
  allocates device memory once per concurrent caller; uploads are fused into a single pass over staging
  memory, and the encrypted matrix crosses the bus once per instance rather than once per batch.
  Finally, WGSL has no 64-bit integers, so each field product is assembled from four 16-bit
  partial products, and the query-major output layout gives warps coalesced reads while
  neighboring workgroups reuse the same matrix row in cache.

== Distillation


#bibliography(title: "Bibliography")

