#import "lib/template.typ": template
#import "lib/bibliography.typ": init-bib
#import "lib/utils.typ": *

#show: template.with(
  dedication: "Dedication or acknowledgements",
  // font: "New Computer Modern",
  font: "",
)

#let (cite, citesec, bibliography) = init-bib(yaml("BIBLIOGRAPHY.yml"))

= Introduction

Large Language Models (LLMs) have proven very useful in various contexts and types of users: some
only use them casually, some to help them study, while others use them to speed up their daily work.
This last category of people finds themselves often having to send prompts which contain private
information, such as parts of their company's code, contracts, or other material which is
intellectual property of the company and, as such, should remain private to the company itself.

While self-hosting open-weight models is always a possibility, individuals and companies often don't
have the required compute capabilities.
Usually entities which don't own their own hardware resort to inference providers (either the
provider of the model themselves or a third party one).
This however could become an issue because classical inference requires the users to sent plain text
to the inference provider, which then will come to know all the possibly private information which
users ask in their queries.

In this work we study an inference model based on Encrypted Matrix-Vector Products (EMVP for short)
#cite(<emvp2025>) which enables efficient computation of linear operations privately.
We study also how a GPT model can be distilled in order to remove as many non-linearities as
possible so that the remaining architecture is more suitable to be used with EMVP.

= Theory

== Encrypted Matrix-Vector Multiplication <sec:emvp>

The fundamental theoretical building block is the Encrypted Matrix-Vector Multiplication based on
Trapdoor Matrices #cite(<emvp2025>), in particular the construction based on the 1D-SLSN assumption.

The protocol works over a prime field $FF_p$. The client holds some matrix
$M in FF_p^(m times ell)$ and some vector $q in FF_p^(ell)$ and wants to delegate to an untrusted
server the computation of $a := M q in FF_p^m$.

To do this, the client encrypts $M ->^(#raw("sk")) hat(M)$ and $q ->^(#raw("sk")) (hat(q), q')$ and
sends $(hat(M), hat(q))$ to the server.
The server computes $M' in FF_p^(m times s)$, where $s$ is the number of blocks of the 1D-SLSN
construction (typically $s << ell$), and sends it back to the client. The client then recovers
$a = M' p' - r'$ from $(M', q')$, where $q' = (p', r')$ is its decoding key.

This protocol turns out to be particularly cheap to run compared to doing a matrix-vector
multiplication in clear text, only being $tilde 1.5$x more costly.

=== Protocol Description

The protocol is made of five algorithms:

/ Key Generation: Generate a private key `sk` for the client, taking as arguments a security
  parameter $lambda$ and the query length $ell$.
  Additional parameters to the EMVP protocol like the code rank $k$, and the 1D-SLSN block size $b$
  are derived from $(lambda, ell)$ using the algorithm presented in #citesec(<emvp2025>, "7.4").
/ Encryption: The client encrypts $M ->^(#raw("sk")) hat(M)$.
  It samples a secret multiplier $g <- FF_p^k$ which defines the systematic code
  $C = (I | M_g) in FF_p^(k times 2k)$ where $M_g$ is a circulant matrix generated by $g$
  #footnote[
    This is the cyclic ring variant presented in Section 3.1 of #cite(<emvp2025>). Since $M_g$ is
    circulant, encoding through $C$ or $D$ is a single cyclic convolution, computable in
    $bigO(k log k)$ field operations.
    Over this ring, however, the cyclic structure interacts badly with the 1D-SLSN block grid
    whenever the block size divides $k$; as prescribed in the same section, the implementation
    therefore permutes the codeword coordinates with a public random permutation $Pi$, applied
    consistently to $hat(M)$ and to every query.
  ].
  Together with its systematic dual $D := [ - M_g^T | I ] in FF_p^(k times 2k)$.
  Each row of $M$ is zero-padded to length $k$, encoded through $D$, masked by adding the
  materialization $R$ of a trapdoored matrix (TDM for short, see @sec:tdm), and permuted by $Pi$:
  $
    hat(M) := Pi (M_"pad" D + R) in FF_p^(m times 2k)
  $
  where $M_"pad"$ denotes $M$ with its rows zero-padded from $ell$ to $k$ coordinates.
/ Query: The client takes a vector $q$ and uses the secret key `sk` to produce the pair
  the encrypted query $hat(q)$ and the decoding key $q' = (p', r')$.
  We first sample $r <- FF_p^k$, then let $c := r^T C in FF^(2k)$ and $tilde(q) := q_"pad" + c$,
  where $q_"pad" in FF_p^k$ is $q$ padded with zeros.
  Then we compute $r' := R tilde(q)$ using the trapdoor in $R$.
  We proceed by sampling $alpha_1, ..., alpha_s <- FF_p without {0}$ and let
  $p' := (alpha_1^(-1), ..., alpha_s^(-1)) in FF_p^s$.
  We then partition $tilde(q)$ in $s$ blocks and multiply each one by $alpha_s$ in order to obtain
  $hat(q) = (alpha_1 q_1 | ... | alpha_s q_s)$.
  We return $(hat(q), (p', r'))$.
/ Answer: This is the only phase which _runs on the server_.
  The server gets $(hat(M), hat(q))$ and splits again in $s$ chunks and we compute
  $
    M' = [hat(M)_1 hat(q)_1 | ... | hat(M)_s hat(q)_s] in FF_p^(m times s)
  $
/ Decrypt: The client then computes $a = M'p' - r' in FF_p^m$.

=== Trapdoored Matrices <sec:tdm>

A Trapdoored Matrix (TDM) is formally defined as the pair $(R, #raw("apply"))$ where
- $R$ is a matrix over $F$, which is undistinguishable from one uniformly sampled from the same
  space;
- The function `apply`$: x mapsto R x$ which is a cheap, secret way to compute $R x$, also referred
  as _trapdoor_.

The TDM concept originates from two independent recursive constructions #cite(<braverman2025>, <vaikuntanathan2025>). In #citesec(<emvp2025>, "5") the authors describe several direct ways to
construct a TDM. In my work I considered three, each for a different reason.

/ Irreducible Ring-LPN: This is the TDM which has the strongest cryptographic foundation.
  The materialized matrix is $R = H E$ with $H = [I | M_a] in FF_p^(k times 2k)$, where the
  public block $M_a$ implements multiplication by a public scalar $a$ in a degree-$k$ irreducible
  extension of $FF_p$, and $E in FF_p^(2k times k)$ is a secret sparse Bernoulli matrix
  #citesec(<emvp2025>, "5.1").
  Pseudorandomness of $R$ then follows from the dual-LPN assumption over the extension ring, whose
  irreducible instantiation is the most conservative choice #cite(<heyse2012>, <boyle2022>).
  The trapdoor computes $x mapsto H (E x)$ as one sparse product followed by a single cyclic
  convolution, in $bigO(k log k)$ field operations.
/ Toeplitz fast product: The first conjecture-based candidate, which trades the LPN foundation
  for speed and universality #citesec(<emvp2025>, "5.2"). The matrix is a product of three
  secret Toeplitz factors interleaved with public random permutations,
  $
    R = S_L Pi_L S Pi_R S_R
  $
  where $S_L$ and $S_R^T$ are $k times 2k$ and $S$ is $2k times 2k$. Each factor is a cyclic
  convolution evaluated in $bigO(k log k)$ through a cached NTT spectrum, so the trapdoor never
  materializes $R$. Security rests on a conjectured degree-3 pseudorandomness property, a
  generalization of the MQ assumption #cite(<matsumoto1988>) whose track record warrants caution
  #cite(<beullens2022>).
/ RAA style: The leanest, most ad hoc candidate, modeled on repeat-accumulate-accumulate codes
  #cite(<divsalar1998>, <guruswami2008>, <brehm2024>). A fixed matrix $D$ repeats each of the
  $k$ input entries $c >= 3$ times, the result passes through rounds of public random
  permutations $Pi_i$ and secret weighted accumulations $S_i$, and $D^T$ finally compresses:
  $ R = D^T Pi_4 S_3 Pi_3 S_2 Pi_2 S_1 Pi_1 D $
  where $(S_i x)_j := sum_(l <= j) w_(i, l) x_l$ is a weighted prefix scan with secret weights,
  which the implementation evaluates with a linear-time scan #cite(<blelloch1993>). Every factor
  is a single linear pass, making this the cheapest of the three, but it inherits the same
  degree-3 conjecture #cite(<matsumoto1988>) with even less supporting analysis.

=== Cryptanalysis

None! I am NOT a cryptographer!

This work assumes that the assumptions in the cited documents are correct and does not try to prove
them independently.

I set the security parameter $lambda = 128$ in the project, but I haven't formally proven
independently that the whole protocol is secure against a malicious server.

My implementation should be correct and follows the constructions in the papers which provide the
algorithms but it hasn't been independently audited and might therefore be flawed.

== Reducing the client roundtrips

The transformer model has become the de facto standard for language models.
Its basic unit, the _transformer block_ #cite(<vaswani2017>), maps a sequence of $d$-dimensional
token vectors to a new sequence of the same length through two sublayers: a self-attention
layer, and a feed-forward network, both wrapped in residual connections and normalization.

Both sublayers contain many linear parts, which are however interleaved by a non-negligible number
of non-linearities. As we discussed previously, these non-linearities, require a roundtrip back to
the client to be computed.
A single (original) transformer block has 1 softmax, 1 activation (usually ReLU/GeLU/SiLU...),
2 normalization: this is already 4 roundtrips per block.
Moreover, even if self-attention is mostly linear, the score $Q K^T$ as well as the
final attention value $A V$ computations are linear operations on two input-dependent matrices and
therefore are not suitable for direct use with EMVP.

There are many studies which attempt to _linearize_ more of the transformer block: some attempt to
remove the softmax in attention, some try to linearize the MLP.
However, for this application this is often not enough: in this work I study whether it is possible
to bring the number of roundtrips per block to 1, or even 0.

TODO: add citations here.

=== Linearizing the transformer

The first question I wanted to try to answer is "How well can a full transformer block be
approximated by a linear transformation?".
There is some experimental research already in this direction #cite(<razzhigaev2024>) which seems to
suggest that, while not all transformer blocks can be replaced, some often can.

If we find a suitable block to be replaced in this way, we can fully fold it into the next matrix,
making it practically free in our protocol.
This is not always possible however: some blocks are highly non-linear, others, even if
linear-looking, cannot be easily replaced without increasing a consistently the perplexity score.
Moreover, while in the low-context-size regime many blocks seem well suited for this kind of
approximation, when the number of tokens being processed increases the non-linearities become more
important and the approximation less precise.

=== A less aggressive approach

When linearizing the whole block is not possible, I still try to remove as many non-linearities as
possible. Since we need already a client roundtrip to compute some attention values, the most well
suited non-linearity to be kept is the `Softmax` in the attention block: in this way we use the same
client roundtrip for both part of the attention calculation as well as computation of the
non-linearity.

These idea has been already analyzed by Jha and Reagen in their "AERO" protocol #cite(<aero2024>).
The authors of this work studied how a model can be trained when `LayerNorm` and the activation
function of the MLP are completely removing, leaving the block in a `Softmax`-only regime.

The study showed that this can lead to an entropy unbalance in the attention heads: in some the
entropy tends to get very high, in some others very low, leading to degradation of the model
performance.
In their study the authors suggest the use of an "Entropy Regularizer" during training which can
mitigate this problem.

While #cite(<aero2024>) train a model from scratch, I study if the same techniques can be applied to
a pre-existing model, in order to distill a more linear one.
When a block can be brought to the `Softmax`-only regime, its attention reduces to
$
  Q = X W_Q, K = X W_K, V = X W_V \
  A = "Softmax"((Q K^t)/(t sqrt(d_k))), Z = A V \
  Y = X + "Concat"(Z_1, ..., Z_H) W_O
$
where we can let the client compute only $A$ and $Z$.

== Related Works

TODO.

= Assumptions <sec:assumptions>

In this work I assume that all the cryptography assumptions in the EMVP protocol are sound and the
choice of parameters is appropriate. When I was in doubt on which parameters to pick I always made
the most conservative choice. This however does not guarantee safety.

Moreover I assume the client machine is fully trusted and that the client owns the weights of the
GPT, therefore the client is allowed to see intermediate values of the decoding process.

Computationally, the server is assumed to be more performant than the client and even have access to
a GPU, while the client is somewhat weaker, having access to a fairly modern multi-core CPU, in
particular one which supports AVX2 #cite(<intel-avx>).
I assume good connectivity between the client and the server: the better the connection the faster
the inference.

A stronger assumption would be that the server has a Trusted Execution Environment (TEE), in which
case the whole client can basically move to the TEE and reduce latency drastically as
non-linearities can be computed in the TEE without ever leaving the server. This study is however
out of scope for the current work.

= Development

The whole code for this project is available at https://github.com/billy4479/emvp-thesis and
https://github.com/billy4479/emvp-model-training\.

== EMVP

I implemented the EMVP protocol in the Rust programming language #cite(<rust>), which provides the
memory safety and the low-level primitives needed for fast execution.

The result is a Cargo workspace containing five crates: two of them contain the application for the
client and the server, the remaining three implement the operations over a finite prime field,
trapdoor matrices, and the actual EMVP protocol.

Each one of the three library crates has been thoroughly tested and benchmarked. I highlight a few
implementation details which I find worth noting.

=== Prime Field Layer

This is really the core the project: all the algebra primitives are located here, therefore it's
important that the code is well optimized, as the performance of everything downstream depends on
them.

Even if the EMVP protocol itself is field-agnostic, fast computation of convolutions needed for the
trapdoored matrices requires a prime field.

/ Vectorization:
  The whole crate is optimized having in mind that the client has access to an `AVX2`-capable CPU,
  which allows a substantial speedup in some algebraic kernels, such as computing NTTs,
  convolutions, dot products, and bulk operations in general.
  Interestingly, I found that LLVM optimizer #cite(<llvm>), when instructed to do so by setting
  `target-cpu = native`, and with some hints and trial and error, generates equivalent or faster
  machine code than handwriting `AVX2` intrinsics.
  This is great news, since it allows to drop the code complexity greatly, avoid many uses of
  `unsafe`, expand portability to non-`x86_64` platforms, like `ARM64`, and even support more
  advanced extensions, like `AVX512`.
  The only tradeoff is that clients have to compile their own version of the software: as this is
  research software I deemed the tradeoff worth it to see how much I could push the performance
  while keeping the project complexity in scope.

/ Compile time modulus:
  These optimizations by the LLVM compiler are also enabled by the fact that the `PrimeFieldLayer`
  struct takes the modulus $p$ as a _compile time_ parameter. This is acceptable since usually $p$
  is fixed beforehand and a program requires a single specialization of `PrimeFieldLayer` anyways.
  #footnote[
    I also wanted to move some length arguments to compile time, such as the size of TDMs, the
    length of the NTT, etc. However, even though I suppose this could lead to further performance
    gains, it effectively ties the compiled program to a single pretrained model (as sizes are
    compile time constants). Moreover, the Rust programming language at the time of writing does
    not support the right primitives to fully implement this idea, Zig #cite(<zig>) would be a
    better choice for this scenario, however it felt too unstable and unsafe to be used in this
    project.
  ]

/ Modular arithmetics:
  Multiplication runs in the Montgomery domain #cite(<montgomery1985>) so a product costs only
  multiplies and bit shifts while conversion happens only at the API boundaries.
  Constant multipliers, such as NTT twiddle factors, instead use Shoup's trick #cite(<shoup2009>):
  precomputing $floor(w dot 2^32 \/ p)$ replaces the reduction with one extra multiply and subtraction.
  All conditional corrections are expressed as branchless mask operations rather than
  comparisons, which lets LLVM vectorize the kernels.

/ Number Theoretical Transform:
  Instead of repeating the work for each transformation, we construct and hold a "plan" for a fixed
  length $N$: the plan computes a suitable root of unity, retains the twiddle factors in precomputed
  tables #cite(<frigo1999>), and picks which butterfly implementation fits the modulus width.
  The forward transform then walks $log_2 N$ stages in place, applying a butterfly to each pair of
  values. Each butterfly is Harvey's lazy variant #cite(<harvey2014>): instead of paying a full
  reduction after every addition and multiplication, residues are carried through in redundant
  intervals and each butterfly performs a single correction, and the slightly unreduced inputs feed
  directly into the wide-input form of Shoup's multiplication #cite(<bradbury2021>).
  A single normalization pass restores canonical residues once, after the last stage.

  Convolutions themselves proceeds in the usual three steps: transform both operands forward,
  multiply pointwise in Montgomery domain, transform the result back, and scale by $N^(-1)$.
  For negacyclic products modulo $x^N + 1$, the inputs are additionally twisted by powers of a
  $2N$-th root of unity before the transforms and untwisted afterwards #cite(<longa2016>).
  All of this reuses the plan's tables, so repeated products pay only the transforms themselves.
  Operands small enough that the $O(N log N)$ machinery is not worth it fall back to schoolbook
  multiplication below a crossover point measured with the benchmark suite.

  Even if this NTT implementation was independently written I compared it to other state of the art
  libraries which implement the same algorithms #cite(<concrete-ntt>, <fasterntt>).


=== Trapdoored Matrices

All TDMs implement the same trait: they need to provide an `apply()` method, which computes the
matrix vector product using the trapdoor, and a `materialize()` method, which returns the equivalent
public dense representation.
Moreover, I `apply()` to be allocation-free, therefore the implementers of the TDM trait should
provide a reusable scratch buffer.

The trapdoor matrix has less "science" behind it's optimizations: where feasible, intermediates are
cached and reused, and I use rayon #cite(<rayon>) to parallelize the paths which benchmarks show
benefit from parallel computation.

=== EMVP Protocol

/ Answer phase:
  This is the hottest code path: it will be executed many times and will is quite expensive to run,
  however it is also easily optimizable.
  The answer phase is basically just a chunked matrix-vector multiplication over a finite field,
  a task which can be easily parallelized.
  We could use rayon again, but by our assumptions (@sec:assumptions), the server has a GPU, which
  we can use to speed up computations drastically.
  I chose to use WGPU #cite(<wgpu>, <wgsl>), instead of more popular alternatives like CUDA, as it
  is open-source, cross-vendor, integrates well with Rust, and the performance loss is negligible
  for the scope of this project.
  Device buffers hold raw Montgomery residues, so no conversion happens on upload or download.
  Compute shares are also compiled on the flight for a specialized prime modulus, while the
  dimensions of each batch travel in a small uniform buffer, so changing protocol parameters never
  triggers a recompilation.

/ Measured crossover:
  Using the GPU is sometimes not necessary, as sending data through PCIe is often expensive. For
  smaller matrices and queries the cost outweighs the benefits. Instead of sending everything to the
  GPU, I measured crossover point where rayon becomes faster than the GPU, and where single core
  becomes faster than rayon.

=== Client-Server architecture

The `client` and `server` crates provide an actually runnable binary to run inference on the
selected model.
These binaries are model-agnostic: they just need the right manifest to tell the client what layers
can be delegated to the servers and which ones cannot, but they should work for models different
than GPT-2.

The client connects to the server via TCP and uploads all the encrypted matrices. The server
generates, for each client connection, an unique identifier for each uploaded matrix.
The client then sends to the server queries in the for `Vec<(matrix_id, Vec<encrypted_vector>)>` so
that the server can compute all those products in parallel, reducing the number of roundtrips
needed.

== Distillation

I focussed my work on GPT-2 124M #cite(<radford2019>). This is a very small model which was chosen
for its simple architecture (only 12 transformer blocks), which allows for fast iteration times for
experiments, even on consumer hardware.
There isn't anything really preventing from applying the same procedure to a bigger model, however
the rest of my work is based on this model, and more sophisticated or bigger models have not been
tested.

Moreover I chose to work with very small context length of 128 tokens. This was done for speed up
the research but there is nothing preventing this study to be performed on longer contexts.

I gave myself a limit on how much the performance of the final model can degrade with respect to the
untouched GPT-2 by deciding that the model perplexity score on a fixed validation portion of the
WikiText dataset #cite(<merity2017>) should not increase more than $5%$.

Each phase follows more or less the same process: fit a linear layer to replace some part of the
original GPT-2 architecture, surgically insert it into the actual model, evaluate the result.
At each phase I allowed the perplexity to go up to a limit of $20%$, then I add a new LoRA layer
#cite(<hu2022>) right after the just introduced linear one while the rest of the weights remain
fixed. If this is enough to make perplexity go down under $5%$ I move to the next layer to be
replaced. If LoRA is not enough I unfreeze all the weights and train again.

All experiments try to stay as deterministic as possible and various intermediates are immutable:
this allows for results to be reproduced and allow, at any point, to jump back to a previous phase.


=== Linearization

As first experiment I computed the Procrustes score for each block, as well as per each attention
and MLP sub-blocks.
While I aim to replace the whole transformer with an affine transformation, this is useful data for
the next phases: it will give good hints on how well will AERO's procedure apply.

I followed a greedy approach: replace the layer with the least perplexity increase, fit and measure
all other layers again and repeat.

=== Softmax-only regime

TODO.

=== Quantization

My implementation of the prime field layer works over `u32`, but the best performance is only
available when the modulus $p < 2^30$.
Since we need to avoid wrap-around, and for GPT-2 the hidden dimension is $d = 768$, to be
completely sure that we will never wrap-around, we can use a signed `int10` precision.

However, once the vectors are decrypted on the client, I convert them to to `float32` precision to
apply `Softmax` attention and other non-linearities. This gives us room to requantize them to the
most appropriate scale.


TODO: complete here if a quantizer-aware fine tune run will needed.

= Results

All benchmarks are run on a desktop PC with a AMD Ryzen 2600X (6 cores, 12 threads, AVX2), 32GB of
RAM, and a GTX 1060 6GB when the machine was at idle using the Criterion library.

== Rust Library

While GPT-2 is quite a small model, the EMVP crate supports larger dimensions. The code is fully
reusable and I hope it might be a fit for future projects and research.

=== TDMs

While Ring-LPN offers the most stable cryptographic foundation it is also the slowest one compared
to the other two. In general RAA style TDMs are much faster than all the others during `Apply`.

#figure(
  image("assets/apply.svg", width: 70%),
  caption: [Timings for `Apply`. This is the hot path which the client will run on each EMVP,
    therefore it is the most important operation to do quickly.],
)
#figure(
  image("assets/construction.svg", width: 70%),
  caption: [ Timings for `Construction`. This happens just once during encryption. ],
)
#figure(
  image("assets/materialize.svg", width: 70%),
  caption: [ Timings for `Materialize` in logarithmic scale.
    This happens just once during construction.
    (This benchmark uses a different smaller matrices than the two figures above as materializing
    matrices takes a lot of RAM, making the benchmarks suite too heavy to run on some less powerful
    machines.)
  ],
)

=== EMVP Protocol

What follows are some plots of the results of the benchmark of the EMVP protocol itself.
I believe these are good results: the full online phase is only slightly slower than a plaintext
computation, also compared to the reference implementation #citesec(<emvp2025>, "F")

#figure(
  image("assets/protocol_phases_ell4096_rows4096.svg", width: 70%),
  caption: [ Timings for different phases of the EMVP protocol, logarithmic scale.
    Plaintext comparison is with Ring-LPN TDM and assumes no communication latency.\
    $ell = 4096, k = 4096$.],
)
#figure(
  image("assets/protocol_phases_ell8192_rows8192.svg", width: 70%),
  caption: [ Timings for different phases of the EMVP protocol, logarithmic scale.
    Plaintext comparison is with Ring-LPN TDM and assumes no communication latency.\
    $ell = 8192, k = 8192$.],
)

== Model

=== Linearization

=== Softmax-only Regime

=== Quantization

= Conclusions

TODO.

== Limitations and Further Work

Download size could be surely optimized using the rate-1 additively homographic encryption scheme
suggested in #citesec(<emvp2025>, "4.1"). However I deemed this out of scope for my thesis, it
should be possible to add it to the Rust crate with without major issues.

Using a model like GPT-2 doesn't really give enough credit to the EMVP protocol, as this size of
model can easily be ran on consumer CPUs. A more in depth study with more compute power, larger and
more sophisticated models could uncover flaws in this work.

= AI Disclosure

While this document is fully hand-written, generative AI was used throughout this project for
research, code writing, generating plots, and for carrying on long repetitive running tasks such as
running benchmarks and training runs.

The use of AI tools was heavily guided by me, I was always in control of the direction of the AI
agents. I fully own any mistake.

The models which helped in completing this work are `GPT-5.6-Sol` and `GLM-5.3-Flash`.


#bibliography(title: "Bibliography")

