#import "lib/template.typ": template
#import "lib/bibliography.typ": init-bib
#import "lib/utils.typ": *

#show: template.with(
  dedication: "Dedication or acknowledgements",
  // font: "New Computer Modern",
  font: "",
)

#let (cite, citesec, bibliography) = init-bib(yaml("BIBLIOGRAPHY.yml"))

= Introduction

Large Language Models (LLMs) have proven very useful in various contexts and types of users: some
only use them casually, some to help them study, while others use them to speed up their daily work.
This last category of people finds themselves often having to send prompts which contain private
information, such as parts of their company's code, contracts, or other material which is
intellectual property of the company and, as such, should remain private to the company itself.

While self-hosting open-weight models is always a possibility, individuals and companies often don't
have the required compute capabilities.
Usually entities which don't own their own hardware resort to inference providers (either the
provider of the model themselves or a third party one).
This however could become an issue because classical inference requires the users to sent plain text
to the inference provider, which then will come to know all the possibly private information which
users ask in their queries.

In this work we study an inference model based on Encrypted Matrix-Vector Products (EMVP for short)
#cite(<emvp2025>) which enables efficient computation of linear operations privately.

= Theory

The fundamental theoretical building block is the Encrypted Matrix-Vector Multiplication based on
Trapdoor Matrices #cite(<emvp2025>), in particular the construction based on the 1D-SLSN assumption.

The protocol works over a prime field $FF_p$. The client holds some matrix
$M in FF_p^(m times ell)$ and some vector $q in FF_p^(ell)$ and wants to delegate to an untrusted
server the computation of $a := M q in FF_p^m$.

To do this, the client encrypts $M ->^(#raw("sk")) hat(M)$ and $q ->^(#raw("sk")) (hat(q), q')$ and
sends $(hat(M), hat(q))$ to the server.
The server computes $M' in FF_p^(m times s)$, where $s$ is the number of blocks of the 1D-SLSN
construction (typically $s << ell$), and sends it back to the client. The client then recovers
$a = M' p' - r'$ from $(M', q')$, where $q' = (p', r')$ is its decoding key.

This protocol turns out to be particularly cheap to run, the original paper shows only a slowdown
compared to clear text of around $50%$, but this will be verified independently.

== Protocol Description <sec:emvp-desc>

The protocol is made of five algorithms:

/ Key Generation: Generate a private key `sk` for the client, taking as arguments a security
  parameter $lambda$ and the query length $ell$.
  Additional parameters to the EMVP protocol like the code rank $k$, and the 1D-SLSN block size $b$
  are derived from $(lambda, ell)$ using the algorithm presented in #citesec(<emvp2025>, "7.4").
/ Encryption: The client encrypts $M ->^(#raw("sk")) hat(M)$.
  It samples a secret multiplier $g <- FF_p^k$ which defines the systematic code
  $C = (I | M_g) in FF_p^(k times 2k)$ where $M_g$ is a circulant matrix generated by $g$
  #footnote[
    This is the cyclic ring variant presented in Section 3.1 of #cite(<emvp2025>).
    Over this ring the cyclic structure interacts badly with the 1D-SLSN block grid whenever the
    block size divides $k$; as prescribed in the same section, the implementation therefore permutes
    the codeword coordinates with a public random permutation $Pi$, applied consistently to $hat(M)$
    and to every query.
  ].
  Together with its systematic dual $D := [ - M_g^T | I ] in FF_p^(k times 2k)$.
  Each row of $M$ is zero-padded to length $k$, encoded through $D$, masked by adding the
  materialization $R$ of a trapdoored matrix (TDM for short, see @sec:tdm), and permuted by $Pi$:
  $
    hat(M) := Pi (M_"pad" D + R) in FF_p^(m times 2k)
  $
  where $M_"pad"$ denotes $M$ with its rows zero-padded from $ell$ to $k$ coordinates.
/ Query: The client takes a vector $q$ and uses the secret key `sk` to produce the pair
  the encrypted query $hat(q)$ and the decoding key $q' = (p', r')$.
  We first sample $r <- FF_p^k$, then let $c := r^T C in FF^(2k)$ and $tilde(q) := q_"pad" + c$,
  where $q_"pad" in FF_p^k$ is $q$ padded with zeros.
  Then we compute $r' := R tilde(q)$ using the trapdoor in $R$.
  We proceed by sampling $alpha_1, ..., alpha_s <- FF_p without {0}$ and let
  $p' := (alpha_1^(-1), ..., alpha_s^(-1)) in FF_p^s$.
  We then partition $tilde(q)$ in $s$ blocks and multiply each one by $alpha_s$ in order to obtain
  $hat(q) = (alpha_1 q_1 | ... | alpha_s q_s)$.
  We return $(hat(q), (p', r'))$.
/ Answer: This is the only phase which _runs on the server_.
  The server gets $(hat(M), hat(q))$ and splits again in $s$ chunks and we compute
  $
    M' = [hat(M)_1 hat(q)_1 | ... | hat(M)_s hat(q)_s] in FF_p^(m times s)
  $
/ Decrypt: The client then computes $a = M'p' - r' in FF_p^m$.

== Trapdoored Matrices <sec:tdm>

A Trapdoored Matrix (TDM) is formally defined as the pair $(R, #raw("apply"))$ where
- $R$ is a matrix over $F$, which is undistinguishable from one uniformly sampled from the same
  space;
- The function `apply`$: x mapsto R x$ which is a cheap, secret way to compute $R x$, also referred
  as _trapdoor_.

The TDM concept originates from two independent recursive constructions #cite(<braverman2025>, <vaikuntanathan2025>). In #citesec(<emvp2025>, "5") the authors describe several direct ways to
construct a TDM. In my work I considered three, each for a different reason.

/ Irreducible Ring-LPN: This is the TDM which has the strongest cryptographic foundation.
  The materialized matrix is $R = H E$ with $H = [I | M_a] in FF_p^(k times 2k)$, where the
  public block $M_a$ implements multiplication by a public scalar $a$ in a degree-$k$ irreducible
  extension of $FF_p$, and $E in FF_p^(2k times k)$ is a secret sparse Bernoulli matrix
  #citesec(<emvp2025>, "5.1").
  Pseudorandomness of $R$ then follows from the dual-LPN assumption over the extension ring, whose
  irreducible instantiation is the most conservative choice #cite(<heyse2012>, <boyle2022>).
  The trapdoor computes $x mapsto H (E x)$ as one sparse product followed by a single cyclic
  convolution, in $bigO(k log k)$ field operations.
/ Toeplitz fast product: The first conjecture-based candidate, which trades the LPN foundation
  for speed and universality #citesec(<emvp2025>, "5.2"). The matrix is a product of three
  secret Toeplitz factors interleaved with public random permutations,
  $
    R = S_L Pi_L S Pi_R S_R
  $
  where $S_L$ and $S_R^T$ are $k times 2k$ and $S$ is $2k times 2k$. Each factor is a cyclic
  convolution evaluated in $bigO(k log k)$ through a cached NTT spectrum, so the trapdoor never
  materializes $R$. Security rests on a conjectured degree-3 pseudorandomness property, a
  generalization of the MQ assumption #cite(<matsumoto1988>).
/ RAA style: The leanest, most ad hoc candidate, modeled on repeat-accumulate-accumulate codes
  #cite(<divsalar1998>, <guruswami2008>, <brehm2024>). A fixed matrix $D$ repeats each of the
  $k$ input entries $c >= 3$ times, the result passes through rounds of public random
  permutations $Pi_i$ and secret weighted accumulations $S_i$, and $D^T$ finally compresses:
  $ R = D^T Pi_4 S_3 Pi_3 S_2 Pi_2 S_1 Pi_1 D $
  where $(S_i x)_j := sum_(l <= j) w_(i, l) x_l$ is a weighted prefix scan with secret weights,
  which the implementation evaluates with a linear-time scan #cite(<blelloch1993>). Every factor
  is a single linear pass, making this the cheapest of the three.


*NOTE*: recent unpublished studies by the authors of the original EMVP paper have found that
Toeplitz and RAA style TDMs can be broken when the permutations are made public. In my work,
permutations never leave the trusted client machine, so they can be considered safe.

== Cryptanalysis

None! I am NOT a cryptographer!

This work assumes that the assumptions in the cited documents are correct and does not try to prove
them independently.

I set the security parameter $lambda = 128$ in the project, but I haven't formally proven
independently that the whole protocol is secure against a malicious server.

My implementation should be correct and follows the constructions in the papers which provide the
algorithms but it hasn't been independently audited and might therefore be flawed.

= Assumptions <sec:assumptions>

In this work I assume that all the cryptography assumptions in the EMVP protocol are sound and the
choice of parameters is appropriate. When I was in doubt on which parameters to pick I always made
the most conservative choice. This however does not guarantee safety.

Moreover I assume the client machine is fully trusted and that the client owns the weights of the
GPT, therefore the client is allowed to see intermediate values of the decoding process.

Computationally, the server is assumed to be more performant than the client and even have access to
a GPU, while the client is somewhat weaker, having access to a fairly modern multi-core CPU, in
particular one which supports AVX2 #cite(<intel-avx>).

These assumptions do not exclude that the client and the server are the same actual machine: the
whole client code could be running inside a Trusted Execution Environment (TEE), which allows for
much better performance and latency than having a network roundtrip in the way.

= Development

_The whole code for this project is available at https://github.com/billy4479/emvp-thesis\._

I implemented the EMVP protocol in the Rust programming language #cite(<rust>), which provides the
memory safety and the low-level primitives needed for fast execution.

The result is a Cargo workspace containing five crates: two of them contain the application for the
client and the server, the remaining three implement the operations over a finite prime field,
trapdoor matrices, and the actual EMVP protocol.

Each one of the three library crates has been thoroughly tested and benchmarked. I highlight a few
implementation details which I find worth noting.

== Prime Field Layer

This is really the core the project: all the algebra primitives are located here, therefore it's
important that the code is well optimized, as the performance of everything downstream depends on
them.

Even if the EMVP protocol itself is field-agnostic, fast computation of convolutions needed for the
trapdoored matrices requires a prime field.

/ Vectorization:
  The whole crate is optimized having in mind that the client has access to an `AVX2`-capable CPU,
  which allows a substantial speedup in some algebraic kernels, such as computing NTTs,
  convolutions, dot products, and bulk operations in general.
  Interestingly, I found that LLVM optimizer #cite(<llvm>), when instructed to do so by setting
  `target-cpu = native`, and with some hints and trial and error, generates equivalent or faster
  machine code than handwriting `AVX2` intrinsics.
  This is great news, since it allows to drop the code complexity greatly, avoid many uses of
  `unsafe`, expand portability to non-`x86_64` platforms, like `ARM64`, and even support more
  advanced extensions, like `AVX512`.
  The only tradeoff is that clients have to compile their own version of the software: as this is
  research software I deemed the tradeoff worth it to see how much I could push the performance
  while keeping the project complexity in scope.

/ Compile time modulus:
  These optimizations by the LLVM compiler are also enabled by the fact that the `PrimeFieldLayer`
  struct takes the modulus $p$ as a _compile time_ parameter. This is acceptable since usually $p$
  is fixed beforehand and a program requires a single specialization of `PrimeFieldLayer` anyways.
  #footnote[
    I also wanted to move some length arguments to compile time, such as the size of TDMs, the
    length of the NTT, etc. However, even though I suppose this could lead to further performance
    gains, it effectively ties the compiled program to a single pretrained model (as sizes are
    compile time constants). Moreover, the Rust programming language at the time of writing does
    not support the right primitives to fully implement this idea, Zig #cite(<zig>) would be a
    better choice for this scenario, however it felt too unstable and unsafe to be used in this
    project.
  ]

/ Modular arithmetics:
  Multiplication runs in the Montgomery domain #cite(<montgomery1985>) so a product costs only
  multiplies and bit shifts while conversion happens only at the API boundaries.
  Constant multipliers, such as NTT twiddle factors, instead use Shoup's trick #cite(<shoup2009>):
  precomputing $floor(w dot 2^32 \/ p)$ replaces the reduction with one extra multiply and subtraction.
  All conditional corrections are expressed as branchless mask operations rather than
  comparisons, which lets LLVM vectorize the kernels.

/ Number Theoretical Transform:
  Instead of repeating the work for each transformation, we construct and hold a "plan" for a fixed
  length $N$: the plan computes a suitable root of unity, retains the twiddle factors in precomputed
  tables #cite(<frigo1999>), and picks which butterfly implementation fits the modulus width.
  The forward transform then walks $log_2 N$ stages in place, applying a butterfly to each pair of
  values. Each butterfly is Harvey's lazy variant #cite(<harvey2014>): instead of paying a full
  reduction after every addition and multiplication, residues are carried through in redundant
  intervals and each butterfly performs a single correction, and the slightly unreduced inputs feed
  directly into the wide-input form of Shoup's multiplication #cite(<bradbury2021>).
  A single normalization pass restores canonical residues once, after the last stage.

  Convolutions themselves proceeds in the usual three steps: transform both operands forward,
  multiply pointwise in Montgomery domain, transform the result back, and scale by $N^(-1)$.
  All of this reuses the plan's tables, so repeated products pay only the transforms themselves.
  Operands small enough that the $O(N log N)$ transformation is not worth it fall back to schoolbook
  multiplication below a crossover point measured with the benchmark suite.

  For negacyclic products modulo $x^N + 1$ (which is implemented in this crate even if the protocol
  does not currently need it), the inputs are additionally twisted by powers of a $2N$-th root of
  unity before the transforms and untwisted afterwards #cite(<longa2016>).

  Even if this NTT implementation was independently written I compared it to other state of the art
  libraries which implement the same algorithms #cite(<concrete-ntt>, <fasterntt>).
  While most of these libraries use handwritten SIMD intrinsics and there are good resources online
  which explain how to implement NTT with SIMD #cite(<seiler2018>, <bradbury2021>) I found that LLVM
  vectorizes the code well, if not better, than hand written techniques from these papers.


== Trapdoored Matrices

All TDMs implement the same trait: they need to provide an `apply()` method, which computes the
matrix vector product using the trapdoor, and a `materialize()` method, which returns the equivalent
public dense representation.
Moreover, I `apply()` to be allocation-free, therefore the implementers of the TDM trait should
provide a reusable scratch buffer.

The trapdoor matrix crate has less "science" behind its optimizations: where feasible, intermediates
are cached and reused, and I use rayon #cite(<rayon>) to parallelize the paths which benchmarks show
benefit from parallel computation.

== EMVP Protocol <sec:emvp-prot>

/ Cyclic ring code variant:
  Originally the authors suggest a generic linear code $C$, with a systematic $D$. While this allows
  for greater flexibility (the server overhead factor can be chosen as an independent parameter,
  allowing to reduce the download size per query), I implemented the variant presented in
  #citesec(<emvp2025>, "3.1") which chooses $C$ and $D$ as presented in @sec:emvp-desc.

  This means that encoding via $C$ or $D$ is a single cyclic convolution, which is $bigO(k log k)$.
  In practice this results in a 20 to 35 times speed-up in the `query` phase over a dense
  non-systematic part, depending on the choice of parameters.

  The downside is that $M_g$ is a $k times k$ matrix and vectors should fit in the systematic
  portion of $D$, giving the constraint $k >= ell$. This in turns means that the server overhead
  factor $f >= 2$
  #footnote[
    There are other possibilities to generate $C$ and $D$ so that encoding stays quasilinear.
    I consider this out of scope for my thesis, see @sec:limit.
  ]
.

/ Answer phase:
  This is the hottest code path: it will be executed many times and will is quite expensive to run,
  however it is also easily optimizable.
  The answer phase is basically just a chunked matrix-vector multiplication over a finite field,
  a task which can be easily parallelized.
  We could use rayon again, but by our assumptions (@sec:assumptions), the server has a GPU, which
  we can use to speed up computations drastically.
  I chose to use WGPU #cite(<wgpu>, <wgsl>), instead of more popular alternatives like CUDA, as it
  is open-source, cross-vendor, integrates well with Rust, and the performance loss is negligible
  for the scope of this project.
  Device buffers hold raw Montgomery residues, so no conversion happens on upload or download.
  Compute shares are also compiled on the flight for a specialized prime modulus, while the
  dimensions of each batch travel in a small uniform buffer, so changing protocol parameters never
  triggers a recompilation.

/ Measured crossover:
  Using the GPU is sometimes not necessary, as sending data through PCIe is often expensive. For
  smaller matrices and queries the cost outweighs the benefits. Instead of sending everything to the
  GPU, I measured crossover point where rayon becomes faster than the GPU, and where single core
  becomes faster than rayon.

== Client-Server architecture

The `client` and `server` crates provide an actually runnable binary to run inference on the
selected model.
These binaries are model-agnostic: they just need the right manifest to tell the client what layers
can be delegated to the servers and which ones cannot, but they should work for models different
than GPT-2.

The client connects to the server via TCP and uploads all the encrypted matrices. The server
generates, for each client connection, an unique identifier for each uploaded matrix.
The client then sends to the server queries in the for `Vec<(matrix_id, Vec<encrypted_vector>)>` so
that the server can compute all those products in parallel, reducing the number of roundtrips
needed.

= Results

All benchmarks are run on a desktop PC with a AMD Ryzen 2600X (6 cores, 12 threads, AVX2), 32GB of
RAM, and a GTX 1060 6GB when the machine was at idle using the Criterion library
#cite(<criterion>).

== TDMs

While Ring-LPN offers the most stable cryptographic foundation it is also the slowest one compared
to the other two. In general RAA style TDMs are much faster than all the others during `Apply`.

#figure(
  image("assets/apply.svg", width: 70%),
  caption: [Timings for `Apply`. This is the hot path which the client will run on each EMVP,
    therefore it is the most important operation to do quickly.],
)
#figure(
  image("assets/construction.svg", width: 70%),
  caption: [ Timings for `Construction`. This happens just once during encryption. ],
)
#figure(
  image("assets/materialize.svg", width: 70%),
  caption: [ Timings for `Materialize` in logarithmic scale.
    This happens just once during construction.
    (This benchmark uses a different smaller matrices than the two figures above as materializing
    matrices takes a lot of RAM, making the benchmarks suite too heavy to run on some less powerful
    machines.)
  ],
)

== EMVP Protocol

TODO

= Conclusions

TODO.

== Limitations and Further Work <sec:limit>

=== Field size

My field is implemented over 32 bits. This choice was made to make the GPU implementation more
practical, as often GPUs don't have access to 64 bits precision, which however can often be
simulated.

I did not explore 64 bits wide prime fields, I believe this would lead to a tradeoff between speed
against quantization precision and complexity.

=== Bringing down the server overhead factor

In my work, I chose to implement the code construction suggested in #citesec(<emvp2025>, "3.1")
without deviating from it. This, as discussed in @sec:emvp-prot, implies $f >= 2$.
I suggest some possible ways to reduce $f$ while keeping encoding through $C$ and $D$ quasilinear.

/ Vandermonde codes:
  This direction is also hinted by the original authors in their reference implementation
  #citesec(<emvp-code>, "linearcode/LinearCode.go") but is however left as a stub.
  This has the technical downside of requiring some NTT trickery such as implementing different
  radix transformations or emulating them with coset-NTT and twisted evaluation.
  Moreover, there isn't any cryptoanalysis work which I could find defending this construction.
/ Truncating the cyclic ring code:
  We could even just choose a circulant $M_g$ as in the original construction and only select $k$
  rows from it for the rest of the construction. This also allows for fast encoding and requires
  less moving parts than the Vandermonde codes, but it's security is also not verified.

=== Reducing the download size

In the 1D-SLSN construction, each vector is split into $s$ blocks. While this has no performance
impact on the computation itself, it increases download size by a factor of $s$, which combined with
the server overhead factor $f$ can be substantial.

The paper suggests #citesec(<emvp2025>, "4.1") that this can be mitigated by using a rate-1 additive
homographic encryption mechanism to the protocol. This suggestion was not investigated in my work.

=== Quantization

Since EMVP works on a field, regular floating point numbers should be quantized before entering the
algorithm.
This could be an issue, since we want to avoid wrap around during the computations.

Luckily, every cloud has a silver lining: since we need to perform a roundtrip to the client anyways
at every non-linearity or attention block, the client can de-quantize the vector, perform
computation with regular floating point arithmetic, and re-quantize the result using a different
scale. This in theory should allow for sufficient precision even for a 32-bit field like mine.

= AI Disclosure

While this document is fully hand-written, generative AI was used throughout this project for
research, code writing, generating plots, and for carrying on long repetitive running tasks such as
running benchmarks and training runs.

The use of AI tools was heavily guided by me, I was always in control of the direction of the AI
agents. I fully own any mistake.

The models which helped in completing this work are `GPT-5.6-Sol` and `GLM-5.3-Flash`.


#bibliography(title: "Bibliography")

