#![expect(
    clippy::unwrap_used,
    reason = "benchmarks use fixed valid parameters and keep setup beside measurements"
)]

//! Sustained client-side throughput of the online query and decrypt phases
//! of the EMVP protocol (IACR ePrint 2025/858, Fig. 1).
//!
//! # Fairness contract and metric
//!
//! One fixed LLM-scale shape (4096-element records against 4096 matrix
//! rows, the plaintext-equivalent of one 7B-class attention projection, and
//! the smallest shape the `gpu` suite pins for the server side)
//! runs with the shared `search(4096, 128)` protocol parameters. Every
//! measured iteration executes on rayon's global pool, so the library's
//! parallel decisions see the machine's pool size and use all of its
//! cores. No GPU is involved: both phases are client-side CPU work.
//!
//! - `query`: one [`query_batch`] call per iteration, the library's
//!   parallel client path. The batch reserves one identifier range and
//!   distributes the queries across the pool workers, each owning a
//!   [`emvp::QueryScratch`] built once per call; every query evaluates the
//!   mask through the trapdoor exactly as the single-query [`emvp::query`]
//!   does. The identifier range keeps advancing across iterations,
//!   mirroring sustained serving with fresh randomness.
//! - `decrypt`: the server answers for a query batch of the same size,
//!   decoded with one [`decode_batch_into`] call per iteration, the
//!   library's parallel client path. It distributes the (answer, decoding
//!   key, output buffer) triples across the pool workers, and each answer's
//!   rows additionally spread across the pool when the row grid clears the
//!   shared dispatch policy. The decoded outputs are standing buffers
//!   reused by every iteration; each call fully overwrites them.
//!
//! [`Throughput::Elements`] counts the batch, so Criterion's elem/s figure
//! is queries per second for `query` and decoded products per second for
//! `decrypt`, directly comparable between the two phases. The query
//! artifacts are freshly allocated per iteration, following the protocol
//! API as written; the decrypt side decodes into preallocated output
//! buffers, matching a client that holds standing storage for a received
//! answer batch.//!
//! Fixtures are built strictly outside timing, per mask suite, from the
//! shared seeded builders of `mod common`. The decrypt fixtures are
//! generated by one [`query_batch`] call against the toeplitz suite's
//! derived state followed by one [`answer_into`] per query, so they are
//! bit-identical to what the measured query path produces. The decode
//! arithmetic is mask-independent, so the decrypt sweep runs once and its
//! numbers stand for every construction, as in the protocol suite's answer
//! and decode phases.
//!
//! # Case IDs and filters
//!
//! Each batch size runs one case per phase under the
//! `client_phase_throughput_v1` group:
//! `client_phase_throughput_v1/{toeplitz,raa,ring}/query/B` and
//! `client_phase_throughput_v1/decrypt/B` for `B` in `1..=256` powers of
//! two. Full sweep with a saved baseline:
//!
//! ```text
//! cargo bench -p emvp --bench client_throughput -- \
//!     --save-baseline client-phase-throughput-v1 'client_phase_throughput_v1'
//! ```
//!
//! Only the largest query batches of one suite; the `--` filter is a
//! regular expression over the full case IDs:
//!
//! ```text
//! cargo bench -p emvp --bench client_throughput -- \
//!     --save-baseline client-phase-throughput-v1-large \
//!     'client_phase_throughput_v1/(toeplitz|ring)/query/(128|256)$'
//! ```
//!
//! Under `--features bench-quick` only the Criterion timing shortens: the
//! shape and the batch sweep are pinned and cannot shrink.

use std::hint::black_box;
use std::time::Duration;

use criterion::{
    BenchmarkGroup, BenchmarkId, Criterion, criterion_group, criterion_main, measurement::WallTime,
};
use emvp::{
    AnswerRef, DecodingKey, DerivedState, EmvpParams, EncryptedMatrix, answer_into,
    decode_batch_into, encrypt, query_batch, search,
};
use prime_field_layer::{FieldElement, PrimeField};
use trapdoor_matrices::TdmMask;

use emvp_bench_common as common;

use common::{
    BlockBuilder, LLM_LAMBDA, MODULUS, MaskSuite, SUITE_RAA, SUITE_RING, SUITE_TOEPLITZ,
    derive_with, elements, field_values, raa_block, ring_block, toeplitz_block,
};

// One 4096 x 4096 attention projection: the smallest shape the `gpu`
// suite pins for the server side, so client and server numbers refer to the
// same protocol instance.
const LLM_RECORD_LENGTH: usize = 4096;
const MATRIX_ROWS: usize = 4096;

// Query-batch sweep: powers of two from one query through 256 queries. Each
// value is the number of client-phase artifacts of one measured iteration;
// 256 queries against the machine's pool leave every worker with a
// sustained run of independent work.
const BATCHES: [usize; 9] = [1, 2, 4, 8, 16, 32, 64, 128, 256];
const MAX_BATCH: usize = 256;

/// One suite's client state and encrypted matrix, sharing one instance:
/// everything the query sweep and the decrypt fixtures need.
struct SuiteFixtures<M: TdmMask<MODULUS>> {
    state: DerivedState<MODULUS, M>,
    encrypted: EncryptedMatrix<MODULUS>,
    record: Vec<FieldElement<MODULUS>>,
}

#[must_use]
fn suite_fixtures<M: TdmMask<MODULUS>>(
    params: EmvpParams,
    suite: MaskSuite,
    build_block: BlockBuilder<M>,
) -> SuiteFixtures<M> {
    let mut state = derive_with(params, MATRIX_ROWS, 0x11, suite.context, build_block);
    let matrix = field_values(MATRIX_ROWS * params.ell, 0x12);
    let encrypted = encrypt(&mut state, &matrix).unwrap();
    let record = field_values(params.ell, 0x13);
    SuiteFixtures {
        state,
        encrypted,
        record,
    }
}

/// One `query_batch` call per iteration on the fixed pool: the library's
/// parallel client query path. The reserved identifier range keeps
/// advancing across iterations.
fn bench_query_case<M: TdmMask<MODULUS>>(
    group: &mut BenchmarkGroup<'_, WallTime>,
    suite: MaskSuite,
    state: &mut DerivedState<MODULUS, M>,
    record: &[FieldElement<MODULUS>],
    batch: usize,
) {
    let queries = vec![record; batch];
    // Elements counts queries, so Criterion's elem/s is queries per second.
    group.throughput(elements(batch));
    group.bench_function(
        BenchmarkId::new(format!("{}/query", suite.label), batch),
        |b| {
            b.iter(|| {
                black_box(query_batch(black_box(&mut *state), &queries).unwrap());
            });
        },
    );
}

/// One suite's decrypt-phase fixtures: the server answers for one maximum
/// query batch plus the matching decoding keys, with standing output
/// buffers. Everything is built once per suite, outside timing.
struct DecryptFixtures<const MODULUS: u32> {
    answers: Vec<Vec<FieldElement<MODULUS>>>,
    decoding_keys: Vec<DecodingKey<MODULUS>>,
    decoded: Vec<Vec<FieldElement<MODULUS>>>,
    instance_id: u128,
    rows: usize,
    blocks: usize,
}

fn decrypt_fixtures<const MODULUS: u32, M: TdmMask<MODULUS>>(
    params: EmvpParams,
    state: &mut DerivedState<MODULUS, M>,
    encrypted: &EncryptedMatrix<MODULUS>,
    record: &[FieldElement<MODULUS>],
) -> DecryptFixtures<MODULUS> {
    let rows = encrypted.rows();
    let blocks = params.blocks().unwrap();
    let records = vec![record; MAX_BATCH];
    // The same parallel path the query cases measure, so the fixture batch
    // is bit-identical to what sustained serving would have produced.
    let artifacts = query_batch(&mut *state, &records).unwrap();
    let zero = PrimeField::<MODULUS>::new().element_u32(0);
    let mut answers = Vec::with_capacity(MAX_BATCH);
    for (query, _key) in &artifacts {
        let mut answer = vec![zero; rows * blocks];
        answer_into(&params, encrypted, query, &mut answer).unwrap();
        answers.push(answer);
    }
    let decoded = vec![vec![zero; rows]; MAX_BATCH];
    DecryptFixtures {
        answers,
        decoding_keys: artifacts.into_iter().map(|(_query, key)| key).collect(),
        decoded,
        instance_id: encrypted.instance_id(),
        rows,
        blocks,
    }
}

/// Decodes `batch` server answers per iteration with one
/// [`decode_batch_into`] call, the library's parallel client decrypt path:
/// the batch distributes across the pool, and each answer's rows
/// additionally spread across the pool when the row grid clears the shared
/// dispatch policy. The answer and output buffers are reused every
/// iteration.
fn bench_decrypt_case(
    group: &mut BenchmarkGroup<'_, WallTime>,
    fixtures: &mut DecryptFixtures<MODULUS>,
    batch: usize,
) {
    let DecryptFixtures {
        answers: answer_values,
        decoding_keys,
        decoded,
        instance_id,
        rows,
        blocks,
    } = fixtures;
    let answers: Vec<AnswerRef<MODULUS>> = answer_values[..batch]
        .iter()
        .zip(&decoding_keys[..batch])
        .map(|(answer, key)| {
            AnswerRef::new(*instance_id, key.query_id(), answer, *rows, *blocks).unwrap()
        })
        .collect();
    let mut outputs: Vec<&mut [FieldElement<MODULUS>]> =
        decoded[..batch].iter_mut().map(Vec::as_mut_slice).collect();
    // Elements counts answers, so Criterion's elem/s is decoded products
    // per second, directly comparable with the query cases.
    group.throughput(elements(batch));
    group.bench_function(BenchmarkId::new("decrypt", batch), |b| {
        b.iter(|| {
            black_box(decode_batch_into(
                black_box(&answers),
                black_box(&decoding_keys[..batch]),
                black_box(&mut outputs),
            ))
            .unwrap();
        });
    });
}

/// The query sweep for one mask suite, on the suite's derived state.
fn run_query_sweep<M: TdmMask<MODULUS>>(
    group: &mut BenchmarkGroup<'_, WallTime>,
    suite: MaskSuite,
    params: EmvpParams,
    build_block: BlockBuilder<M>,
) {
    let mut fixtures = suite_fixtures(params, suite, build_block);
    for &batch in &BATCHES {
        bench_query_case(group, suite, &mut fixtures.state, &fixtures.record, batch);
    }
}

/// The decrypt sweep, once. The decoding arithmetic is mask-independent, so
/// the toeplitz fixtures stand in for every construction, as in the
/// protocol suite's answer and decode phases; the decrypt fixtures are
/// built from one more query batch against that suite's encrypted matrix.
fn run_decrypt_sweep<M: TdmMask<MODULUS>>(
    group: &mut BenchmarkGroup<'_, WallTime>,
    params: EmvpParams,
    fixtures: &mut SuiteFixtures<M>,
) {
    let mut decrypt = decrypt_fixtures(
        params,
        &mut fixtures.state,
        &fixtures.encrypted,
        &fixtures.record,
    );
    for &batch in &BATCHES {
        bench_decrypt_case(group, &mut decrypt, batch);
    }
}

fn client_throughput_benches(criterion: &mut Criterion) {
    let params = search(LLM_RECORD_LENGTH, LLM_LAMBDA).unwrap();
    println!(
        "client throughput suite at ell = {LLM_RECORD_LENGTH}, rows = {MATRIX_ROWS}: \
         k = {}, b = {}, n = {}, s = {}, lambda = {}, batches up to {MAX_BATCH}",
        params.k,
        params.b,
        params.n().unwrap(),
        params.blocks().unwrap(),
        params.lambda,
    );
    let mut group = criterion.benchmark_group("client_phase_throughput_v1");
    let mut toeplitz = suite_fixtures(params, SUITE_TOEPLITZ, toeplitz_block);
    for &batch in &BATCHES {
        bench_query_case(
            &mut group,
            SUITE_TOEPLITZ,
            &mut toeplitz.state,
            &toeplitz.record,
            batch,
        );
    }
    run_decrypt_sweep(&mut group, params, &mut toeplitz);
    drop(toeplitz);
    run_query_sweep(&mut group, SUITE_RAA, params, raa_block);
    run_query_sweep(&mut group, SUITE_RING, params, ring_block);
    group.finish();
}

fn criterion_config() -> Criterion {
    bench_common::criterion_tuned(10, Duration::from_secs(1), Duration::from_secs(3))
}

criterion_group! {
    name = benches;
    config = criterion_config();
    targets = client_throughput_benches
}
criterion_main!(benches);
