[package]
name = "emvp"
version = "0.1.0"
edition = "2024"

[lib]
bench = false

[dependencies]
prime-field-layer = { path = "../prime-field-layer" }
rand_chacha = { workspace = true }
rand_core = { workspace = true }
rayon = { workspace = true }
trapdoor-matrices = { path = "../trapdoor-matrices" }

[dev-dependencies]
allocation-counter = { workspace = true }
bench-common = { path = "../prime-field-layer/benches/common" }
criterion = { workspace = true }
proptest = { workspace = true }

[features]
bench-huge = ["bench-common/huge"]

[lints]
workspace = true

[[bench]]
name = "protocol"
harness = false
