[package]
name = "trapdoor-matrices"
version = "0.1.0"
edition = "2024"

[features]
bench-quick = []

[lints]
workspace = true

[dependencies]
prime-field-layer = { path = "../prime-field-layer" }
rand_core = { workspace = true }

[dev-dependencies]
allocation-counter = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
rand_chacha = { workspace = true }

[[bench]]
name = "tdm"
harness = false
